### ISSUE TITLE
QRCodeReader sometimes fails to extract a qr code from an image

### ISSUE THREAD

**Issue by krvs-esoptra** [makiuchi-d/gozxing#10]
The QRCodeReader fails to extract the QR code from the attached image:
![img_0448](https://user-images.githubusercontent.com/33353997/48713629-2427fe00-ec11-11e8-8057-eb555cac5a03.jpg)

It responds with a NotFoundException
Go snippet:
```
...
img, _, _ := image.Decode(file)
bmp, _ := gozxing.NewBinaryBitmapFromImage(img)
qrReader := qrcode.NewQRCodeReader()
result, err := qrReader.Decode(bmp, nil)
...
```

The Java equivalent (https://github.com/zxing/zxing) on the other hand is able to do it
Java snippet:

```
...
LuminanceSource source = new BufferedImageLuminanceSource(image);
BinaryBitmap bitmap = new BinaryBitmap(new GlobalHistogramBinarizer(source));
Reader reader = new QRCodeReader();
Result theResult = reader.decode(bitmap, null);
...
```

**Comment by makiuchi-d** [comment]
`NewBinaryBitmapFromImage` uses `HybridBinarizer` instead of `GlobalHistgramBinarizer`.
Please try this:
```
img, _, _ := image.Decode(file)
src := gozxing.NewLuminanceSourceFromImage(img)
bmp, _ := gozxing.NewBinaryBitmap(gozxing.NewGlobalHistgramBinarizer(src))
qrReader := qrcode.NewQRCodeReader()
result, err := qrReader.Decode(bmp, nil)
```
I got a result without error.

**Comment by krvs-esoptra** [comment]
Yes, indeed it is working for all my images when explicitly specifying the GlobalHistgramBinarizer.
Thank you so much
