### ISSUE TITLE
cannot decode a qrcode

### ISSUE THREAD

**Issue by Linvas** [makiuchi-d/gozxing#13]
I try to decode a qrcode, but I cannot decode it. 
it give me a error 
> NotFoundException

but actully it is a normal qrcode, this is my pic. 
![QR](https://github.com/tuotoo/qrcode/blob/master/example/qrcode11.png?raw=true)

that my code:
```go
func DecodeFile(fi string)(string, error) {
	file, _ := os.Open(fi)
	img, _, _:= image.Decode(file)
	// prepare BinaryBitmap
	bmp, _:= gozxing.NewBinaryBitmapFromImage(img)
	// decode image
	result, err := qrcode.NewQRCodeReader().Decode(bmp, nil)
	if err != nil {
		return "", err
	}
	return result.String(), nil
}
```

**Comment by makiuchi-d** [comment]
That qrcode is distorted.
There is 3px width modules and 4px width modules.

This is fixed image:
![qrcode11fix](https://user-images.githubusercontent.com/1674313/53488990-3698ba00-3ad3-11e9-99cf-a7b30276713c.png)

**Comment by Linvas** [comment]
thank you!!
