### ISSUE TITLE
Can't read qrcodes from github.com/chai2010/qrcode

### ISSUE THREAD

**Issue by JamesCullum** [makiuchi-d/gozxing#14]
Hey makiuchi,

Thank you for the great and active development!
I am currently trying to generate and read qr codes within Go.

The only kinda fast encoding library I found was at github.com/chai2010/qrcode. However, the decoding from the wrapped libqrencode is unable to read the codes generated by itself, as can be seen here: https://github.com/chai2010/qrcode/issues/2

I generated a sample file with the maximum bytes:
![QRCode](https://i.imgur.com/7z3GWRl.png)

As the online version of Zxing was able to read it (it's just "Hello World. " repeatedly), I hoped that this library can read it. Sadly, it doesn't.

Do you know

1. Why decoding doesn't work?
2. What's your recommended approach to quickly encode & decode qr codes, if the issue is within the encoding library?

**Comment by JamesCullum** [comment]
Just learned that the library also has a qrcode write component.
However I was unable to find a way to get the ByteMatrix into an image.Image / save it as file.

**Comment by makiuchi-d** [comment]
Thank you for reporting.

I got same results by original Zxing library too, and I found the 1st image can be read with `DecodeHintType_PURE_BARCODE`.
The 2nd image cannot be read by both libraries.

It seems to be a problem of position detection (original library has same problem).

I'm modifying the exceptions to make the call-stack traceable in the `xerrors` branch.
You can get more information about the error using that branch.

**Comment by JamesCullum** [comment]
Hey @makiuchi-d, 

thank you for the useful reply.
So you would suggest using the other library for encoding?
Or can you make my sample encoding work - basically encoding the maximum amount of binary bytes?

I would love to use pure Go and the same library for en- & decoding.

**Comment by makiuchi-d** [comment]
I found that gozxing could generate the wrong qrcode.
I will fix.

**Comment by makiuchi-d** [comment]
Position detection problem was solved.
Now it is readable without DecodeHint.

**Comment by JamesCullum** [comment]
Thank you very much! However, I still have the following two images encoding the same data. One came directly from the encoder and works, the other one was converted slightly and doesn't work anymore, despite being almost identical.

You can find both images here to try it yourself: https://imgur.com/a/JR1wLJz

**Comment by makiuchi-d** [comment]
Use `PURE_BARCODE` hint or `RotateCounterClockwise()` for that images.
This is completely same behavior with original library.

**Comment by JamesCullum** [comment]
The issue is that if I use `PURE_BARCODE` I can only decode one image, and if I don't use it, I can only decode the other.

You can find both images for testing here: https://imgur.com/a/ejyvNrm

Without `PURE_BARCODE` I get `NotFoundException: dimension = 103` for the one, with it I get `NotFoundException: right = 1554, width = 1480` for the other one.

**Comment by makiuchi-d** [comment]
The first image (aaMEABt.png) is too complex so, finder pattern detector could return wrong result.
PURE_BARCODE hint could be helpful in this case.

The second image (wC3AJmF.png) is not a pure barcode which is blurred.
Don't use PURE_BARCODE hint.

**Comment by JamesCullum** [comment]
So why is the second one not a pure barcode, but the first one is?
Both are generated by the same algorithm and just have a different amount of data in it.

**Comment by makiuchi-d** [comment]
The pure barcode must not be transformed (resized, rotated, deformed) and must contain only black and white pixels.

The second image contains middle color pixels.
