### ISSUE TITLE
Can't decode qr, but zxing online decode correctly

### ISSUE THREAD

**Issue by Mxrck** [makiuchi-d/gozxing#23]
First of all, thanks for this great pure go port.

I'm having a problem with a qr extracted from a pdf, I'm saving it to a jpg before trying to decode

![imagen](https://user-images.githubusercontent.com/2360493/60675310-afbd6a80-9e41-11e9-973e-d010e77b860b.png)

The code I'm using is this

```golang
qrImage := args[0]
qrFile, _ := os.Open(qrImage)
img, _, _ := image.Decode(qrFile)

bmp, err := gozxing.NewBinaryBitmapFromImage(img)
handleError(err) // this only print the error

qrReader := qrcode.NewQRCodeReader()
result, err := qrReader.Decode(bmp, nil)
handleError(err)

fmt.Println(result)
```

This code is showing not found exception, but zxing online shows the following

![imagen](https://user-images.githubusercontent.com/2360493/60675535-3bcf9200-9e42-11e9-8d19-6cf24c34bb49.png)

I try also with hints (maybe I'm doing it wrong)

```golang
hints :=  map[gozxing.DecodeHintType]interface{}{
	gozxing.DecodeHintType_PURE_BARCODE: true,
	gozxing.DecodeHintType_POSSIBLE_FORMATS: []gozxing.BarcodeFormat{
		gozxing.BarcodeFormat_DATA_MATRIX },
}
result, err := qrReader.Decode(bmp, hints)
```

with format exception.

Need some help, because the users will be loading the pdf dynamically

**Comment by makiuchi-d** [comment]
This is a DataMatrix, not a QR Code.
DataMatrixReader was already ported.
