### ISSUE TITLE
NotFoundException: startSize = 0

### ISSUE THREAD

**Issue by childeYin** [makiuchi-d/gozxing#24]
"errVerbose":"NotFoundException: startSize = 0:
qukan-ugc/vendor/github.com/makiuchi-d/gozxing/qrcode/detector.(*FinderPatternFinder).SelectBestPatterns
/data/jenkins/home/workspace/techcenter_content_server-ugc-api/src/qukan-ugc/vendor/github.com/makiuchi-d/gozxing/qrcode/detector/finder_pattern_finder.go:459

**Comment by makiuchi-d** [comment]
It means that no finder pattern detected on your image.

**Comment by childeYin** [comment]
> It means that no finder pattern was detected on your image.

thank you

**Comment by childeYin** [comment]
`

         image, imageName, err := image.Decode(bytes.NewReader(fileBytes))
	if err != nil {
		logger.Logger.Error("qrcode decode failed ", zap.Any("fileBytes len", len(fileBytes)), zap.Any("imageName", imageName), zap.Any("err", err))
		return ""
	}
	bmp, _ := gozxing.NewBinaryBitmapFromImage(image)

	qrReader := qrcode.NewQRCodeReader()
	result, err := qrReader.Decode(bmp, nil)`

fileBytes len":71058,"imageName":"jpeg","err":"NotFoundException: startSize = 0","errVerbose":"NotFoundException: startSize = 0 【or startSize =2】

**Comment by makiuchi-d** [comment]
The QR-Code must contains three finder patterns.
Why don't you show me THE IMAGE?

**Comment by childeYin** [comment]
> The QR-Code must contains three finder patterns.
> Why don't you show me THE IMAGE?

beacuse, image is online by user send, but offline test, it's ok
