### ISSUE TITLE
Barcode recognition on scanned pages

### ISSUE THREAD

**Issue by koltyakov** [makiuchi-d/gozxing#26]
Hi @makiuchi-d,

First off, thank you for such a great library!

I have a question. In a scenario of scanning documents, where the content area is large and barcode presence percentage is relatively small, what might be a recommended approach? Using scanned pages' images as is doesn't work, no barcodes are found on a page. As a workaround, I used cropping the image leaving only top-right area (a potential place of a barcode) for example. That worked, but I'm not sure, probably there is some more robust approach embedded to the library which I just missed?

**Comment by makiuchi-d** [comment]
It is inevitable that something outside the QR code area will cause a detection error.
So, it is better to crop before scanning the QR code.

**Comment by koltyakov** [comment]
Thanks for the confirmation.
