### ISSUE TITLE
FormatException: IllegalArgumentException: versionNumber = 0

### ISSUE THREAD

**Issue by lscgzwd** [makiuchi-d/gozxing#27]
The file to decode: https://pyds.oss-cn-beijing.aliyuncs.com/uploads/test-data/2019-11-13/deskewed/09e0789b-8ada-4ff4-bc81-3339c805eedf.png

My cellphone can scan it.

**Comment by makiuchi-d** [comment]
There are many QRCodes in this image.
Crop a QR-code from the image before scanning, or use `QRCodeMultiReader`.

**Comment by lscgzwd** [comment]
I have tried to crop it before read it. Still error.

**Comment by lscgzwd** [comment]
![image](https://user-images.githubusercontent.com/7054255/68769398-30496e80-065f-11ea-9b85-5011cd16d821.png)

**Comment by lscgzwd** [comment]
My code
`// 图片切成4份，一张图片上有多个二维码时，只能识别其中一个，需要切成四等份，识别出每份中的二维码
	var subImages = make([]*image.RGBA, 0)
	// 尽力只切出二维码，避免干扰
	subY1 := int(math.Round(float64(height) * 0.07))
	subY2 := int(math.Round(float64(height) * 0.227))
	subY3 := int(math.Round(float64(height) * 0.773))
	subY4 := int(math.Round(float64(height) * 0.93))
	subX1 := 0
	subX2 := int(math.Round(float64(width) * 0.1))
	subX3 := int(math.Round(float64(width) * 0.9))
	subX4 := width

	subImages = append(subImages, rgbImg.SubImage(image.Rect(subX1, subY1, subX2, subY2)).(*image.RGBA)) // 图片裁剪x0 y0 x1 y1 左上
	subImages = append(subImages, rgbImg.SubImage(image.Rect(subX3, subY1, subX4, subY2)).(*image.RGBA)) // 图片裁剪x0 y0 x1 y1 右上
	subImages = append(subImages, rgbImg.SubImage(image.Rect(subX1, subY3, subX2, subY4)).(*image.RGBA)) // 图片裁剪x0 y0 x1 y1 左下
	subImages = append(subImages, rgbImg.SubImage(image.Rect(subX3, subY3, subX4, subY4)).(*image.RGBA)) // 图片裁剪x0 y0 x1 y1 右下

	var data = make([]QRCode, 0)
	for index, subImg := range subImages {
		// 识别二维码  二维码定位点顺序：左下、左上，右上、右下（数据区）
		// prepare BinaryBitmap
		bmp, _ := gozxing.NewBinaryBitmapFromImage(subImg)

		// decode image
		qrReader := qrcode2.NewQRCodeReader()
		hints := make(map[gozxing.DecodeHintType]interface{})
		hints[gozxing.DecodeHintType_POSSIBLE_FORMATS] = []gozxing.BarcodeFormat{
			gozxing.BarcodeFormat_QR_CODE,
		}
		hints[gozxing.DecodeHintType_TRY_HARDER] = true
		result, err := qrReader.Decode(bmp, hints)
		if err == nil {`

**Comment by makiuchi-d** [comment]
I found that It caused by miss detection of finder patterns, and it is same behavior of the original ZXing java library.

I got a fine result with `QRCodeMultiReader` in `gozxing/multi/qrcode`.

**Comment by lscgzwd** [comment]
Thanks for reply.
Yes, works fine with QRCodeMultiReader.
Dose this can been fixed ?

**Comment by makiuchi-d** [comment]
If the original ZXing is fixed, I will port that.
