### ISSUE TITLE
请问你如何实现艺术类的二维码呢

### ISSUE THREAD

**Issue by fenglijunnb** [makiuchi-d/gozxing#30]
![it399 com qrcode2](https://user-images.githubusercontent.com/48191768/77719485-56751700-7020-11ea-895b-1b398b59e5d8.jpg)

**Comment by makiuchi-d** [comment]
没有这样的功能。

**Comment by fenglijunnb** [comment]
那请问你能实现这样的功能吗

**Comment by makiuchi-d** [comment]
QR码标准不包这样的艺术类的二维码。

**Comment by fenglijunnb** [comment]
是的，他好像是需要算法进行替换数据。不知道你能不能实现一个例子出来呢

**Comment by makiuchi-d** [comment]
zxing.Writer.Encoder() generates a BitMatrix.
And you can get which pixels are black or white from BitMatrix.Get(x, y).
So you get the artistic 2d-code by puting some artistic image to corresponding position to the black pixels.

**Comment by fenglijunnb** [comment]
但我还是想问一下你能不能实现出来一个例子，素材的话我可以提供包，你看是否能行

**Comment by makiuchi-d** [comment]
我不想做
