### ISSUE TITLE
Datamatrix reader programming

### ISSUE THREAD

**Issue by stephan57160** [makiuchi-d/gozxing#32]
Is there a plan to implement "reader programming" support with Datamatrix ?

Got something, working with Datalogic scanners ...
in case ...

**Comment by makiuchi-d** [comment]
This project is a port of [ZXing](/zxing/zxing).
Original ZXing [does not support](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/datamatrix/decoder/DecodedBitStreamParser.java#L159) "reader programming" now.
I will port if original supports that.

**Comment by stephan57160** [comment]
ok. fine .........
