### ISSUE TITLE
Code128 - Problem with FNC1/FNC2/FNC3 

### ISSUE THREAD

**Issue by stephan57160** [makiuchi-d/gozxing#33]
I need to play with Code128 and FNC3, but ... facing some troubles...

From the sources, I understand my code should look like :
```
        ...
	data := "\u00f3FOO"
	writer := oned.NewCode128Writer()
	bmx, err := writer.Encode(data, gozxing.BarcodeFormat_CODE_128, w, h, nil)
	if err != nil {
		fmt.Printf("Encoder error : %s\n", err)
                return err
	}
	...
```

With the code above, I get an error like : ```Bad character in input: 195```

I had deeper look to code128 encoder and I suspect a bug in this area:
```	// Check content
	for i := 0; i < length; i++ {
		c := contents[i]
		switch c {
		case code128ESCAPE_FNC_1, code128ESCAPE_FNC_2, code128ESCAPE_FNC_3, code128ESCAPE_FNC_4:
			break
		default:
			if c > 127 {
				// support for FNC4 isn't implemented, no full Latin-1 character set available at the moment
				return nil, gozxing.NewWriterException(
					"IllegalArgumentException: Bad character in input: %v", c)
			}
		}
	}
```
With traces inserted, none of the case code128ESCAPE_FNC_x are hit.

I suspect a kind of problem like in the playground : https://play.golang.org/p/cfPXCJsBN3a

**Comment by stephan57160** [comment]
To my understanding...

`c := contents[i]` will assign a single byte to `c`.
As `code128ESCAPE_FNC_x` are actually UNICODE (due to \u), they require 2 bytes.

I tried to replace the sequence 
```	
for i := 0; i < length; i++ {
		c := contents[i]
```
by 
```
for _, c := range contents {
```
This works here, but still fails later.

**Comment by makiuchi-d** [comment]
You are right.
The `contents` must be handled as a array of rune.

**Comment by stephan57160** [comment]
I tried to do so, but ... 
Not that easy ...

**Comment by stephan57160** [comment]
I suppose you'll have the same, in some other encoders, at least, as soon as there is a STRING and a comparison with FNCx like stuff. I'm thinking of DATAMATRIX too, for instance, but possibly not only.

**Comment by makiuchi-d** [comment]
@stephan57160 
I fixed code128 encoder. Please check it.

I checked DATAMATRIX code, but it doesn't have the problem like code128.
The `HighLevelEncoder_MACRO_*_HEADER` of DataMatrix encoder contains a Unicode sequence like code128, 
but that is compared as string, not as bytes.

**Comment by makiuchi-d** [comment]
PR merged.

**Comment by stephan57160** [comment]
OK. 
I'll try to find some time this WE.
Thx.
