### ISSUE TITLE
Please add some examples, encoder and decoder?

### ISSUE THREAD

**Issue by hitzhangjie** [makiuchi-d/gozxing#35]

**Comment by makiuchi-d** [comment]
What type of barcode example do you need?
An example of a QR code decoder can be found in README.md.

**Comment by angelogeminiani** [comment]
Can you please add an example about encoder usage?
How to save data on image?

**Comment by makiuchi-d** [comment]
@angelogeminiani 
I add a generating barcode example in README.md.

`*BitMatrix` generated by the `gozxing.Writer.Encode()` implements the `image.Image` interface.
So, you can save to a image file by the Go's standard way.
