### ISSUE TITLE
error while parsing qr code image

### ISSUE THREAD

**Issue by joicemjoseph** [makiuchi-d/gozxing#36]
I am getting error while trying to parse qr code png image.

`"NotFoundException: (w, h) = (492, 492),  (x, y) = (63, -7)"`
is the error message I am getting. 

I am sorry, I cant attach the sample QR code with you.

### code
```
f, _ = ioutils.ReadFile(filepath)
require.NoError(t, err)
img, _, err := image.Decode(f)
require.NoError(t, err)

bmp, err := gozxing.NewBinaryBitmapFromImage(img)
require.NoError(t, err)
// decode image
qrReader := qrcode.NewQRCodeReader()
result, err := qrReader.Decode(bmp, nil)
require.NoError(t, err) // Error is thrown here.

```

**Comment by makiuchi-d** [comment]
`y=-7` seems to be an invalid value, but I'm not sure without the sample QR code.

**Comment by joicemjoseph** [comment]
but the qr code is valid. I tried with another library and it worked fine.

**Comment by makiuchi-d** [comment]
I mean, show me that qr code.
