### ISSUE TITLE
NotFoundException: startSize = 0

### ISSUE THREAD

**Issue by nightlord189** [makiuchi-d/gozxing#43]
Could you please check, why qrReader.Decode(img, nil) returns error "NotFoundException: startSize = 0"?

#24 
![img3](https://user-images.githubusercontent.com/16045193/125578192-64314e11-f590-4c99-ba5b-9dcaffa92dc7.jpg)

File is attached, QR-code looks normal.
Online version doesn't decode it too.

**Comment by makiuchi-d** [comment]
There are many white spots in the right-top finder pattern, so it cannot be detected.
I got the result by filling it black.

![right-top](https://user-images.githubusercontent.com/1674313/125611140-dd949169-4708-45c6-9f87-00dd10a7bab7.png)

You can know which finder patterns were detected using following decoder hint:
```go
	hints := map[gozxing.DecodeHintType]interface{}{
		gozxing.DecodeHintType_NEED_RESULT_POINT_CALLBACK: gozxing.ResultPointCallback(
			func(p gozxing.ResultPoint) {
				fmt.Printf("resultpoint: %v\n", p)
			}),
	}
```

**Comment by nightlord189** [comment]
> There are many white spots in the right-top finder pattern, so it cannot be detected.

Thanks you! Do you provide any recommendations for these cases? Maybe convert/reduce resolution of source image?
I use your library for recognizing scans from printed papers A4, possibly printers sometimes could print those spots.

**Comment by makiuchi-d** [comment]
I think it should be applied a denoising filter (e.g. median filter) before scanning.
