### ISSUE TITLE
How reading EAN?

### ISSUE THREAD

**Issue by eleimt** [makiuchi-d/gozxing#47]
Give an example of reading ENA from a file please...

**Comment by makiuchi-d** [comment]
Please see the scanning QR code example in README.md, and replace `qrcode.NewQRCodeReader()` to `oned.NewEAN13Reader()` or `oned.NewEAN8Reader()`.
Or use `oned.NewMultiFormatUPCEANReader(nil)` which supports both EAN8 and EAN13.

**Comment by Vanclief** [comment]
@makiuchi-d Unable to scan EAN, tried with those 3 readers but always get `Error NotFoundException`. Tried with hints and without hints.

![ean13 (1)](https://github.com/makiuchi-d/gozxing/assets/13844339/c2a59ebc-9d3d-4dc4-95fe-3e725cf5a83a)

```
	onedReader := oned.NewMultiFormatUPCEANReader(nil)
	res, err := onedReader.DecodeWithoutHints(bmp)
	if err != nil {
		fmt.Println("OnedReader Error", err)
	}

	fmt.Println(res)
```

**Comment by makiuchi-d** [comment]
@Vanclief 
A "quit zone" is required on the right side of the image.
Please don't reduce the white margin, as it holds significance.

**Comment by Vanclief** [comment]
Hi @makiuchi-d, thanks for the reply.

I added some extra space to the right:

![image](https://github.com/makiuchi-d/gozxing/assets/13844339/7f435a8d-1f1a-440b-92ae-1bf6628aa1f9)

Still getting: `NotFoundException: NotFoundException: Couldn't find enough finder patterns (0)`

Is there a reliable way to manipulate the image to avoid this issue?

**Comment by makiuchi-d** [comment]
I got a result: 0123456789012
Please check your environment.

```
package main

import (
	"fmt"
	"image"
	_ "image/png"
	"os"

	"github.com/makiuchi-d/gozxing"
	"github.com/makiuchi-d/gozxing/oned"
)

func main() {
	f, err := os.Open("240935979-7f435a8d-1f1a-440b-92ae-1bf6628aa1f9.png")
	if err != nil {
		panic(err)
	}

	img, _, err := image.Decode(f)
	if err != nil {
		panic(err)
	}

	bmp, err := gozxing.NewBinaryBitmapFromImage(img)
	if err != nil {
		panic(err)
	}

	onedReader := oned.NewMultiFormatUPCEANReader(nil)
	res, err := onedReader.DecodeWithoutHints(bmp)
	if err != nil {
		fmt.Println("OnedReader Error", err)
	}

	fmt.Println(res)

}
```

**Comment by Vanclief** [comment]
My bad, I was still passing the previous image, with the extra padding it works. 

Thank you
