### ISSUE TITLE
not support large image

### ISSUE THREAD

**Issue by RelicOfTesla** [makiuchi-d/gozxing#48]
raw qrcode
```
https://github.com/makiuchi-d/gozxing
```
when size large then 4000x4000 return "NotFoundException: startSize = x:"

![test](https://user-images.githubusercontent.com/4145299/169712740-8cb52ee3-9342-4ef5-be71-86f8aa13909d.png)

**Comment by RelicOfTesla** [comment]
```
 ReedSolomonException: Error locator degree does not match number of roots:
```
![test](https://user-images.githubusercontent.com/4145299/169712946-34bcba02-b191-43cc-8879-e3605dfe8992.png)

**Comment by makiuchi-d** [comment]
The qr-codes in these images are not square (2535x2690 and 2815x2895).
That is why they could not be read correctly.

You should keep the aspect ratio when resizing the image.
The first qr-code can be read by resizing it to a square.
![resized](https://user-images.githubusercontent.com/1674313/172841302-2f5a530b-4d34-4f2e-88f5-2ca39b0154c1.png)

**Comment by RelicOfTesla** [comment]
ok..."zxing.org" also dose not work...
but [ZBar](http://zbar.sourceforge.net/) can be work...

**Comment by RelicOfTesla** [comment]
https://github.com/micjahn/ZXing.Net
ZXing.Net.DemoClients.0.16.8.0\Clients\WindowsFormsDemo\WindowsFormsDemo.exe
Options - GlobalHistogramBinarizer - checked
it's work to my bad picture file
