### ISSUE TITLE
NotFoundException: startSize = 1

### ISSUE THREAD

**Issue by gunnrcrakr** [makiuchi-d/gozxing#49]
IMG: https://i.imgur.com/UoRQWJE.jpg

I got this error from result, err := qrReader.Decode(bmp, nil)

**Comment by makiuchi-d** [comment]
The illustration on the bottom of the image seems to be noise for binarization.

Trim the image before binarization like this:
```
	img, _, _ := image.Decode(file)

	img = img.(interface {
		SubImage(image.Rectangle) image.Image
	}).SubImage(image.Rect(0, 0, 838, 1800))

	bmp, _ := gozxing.NewBinaryBitmapFromImage(img)
```
