### ISSUE TITLE
Unable to decode some QR codes

### ISSUE THREAD

**Issue by awaisbashir** [makiuchi-d/gozxing#51]
Hi
Thanks for the library first. It's working well. However for some QR codes it doesn't able to find QR codes. I've also tried some hints e.g. Try harder. But it doesn't work. The code I've been trying with is;

`bmp, err := gozxing.NewBinaryBitmap(gozxing.NewGlobalHistgramBinarizer(gozxing.NewLuminanceSourceFromImage(img)))
hints := map[gozxing.DecodeHintType]interface{}{
	gozxing.DecodeHintType_TRY_HARDER: true,
	gozxing.DecodeHintType_POSSIBLE_FORMATS: []gozxing.BarcodeFormat{
		gozxing.BarcodeFormat_QR_CODE},
}

// decode image
qrReader := qrcode.NewQRCodeReader()
result, err := qrReader.Decode(bmp, hints)`

And the QR codes, which doesn't decode/detected are the following.
![d7p](https://user-images.githubusercontent.com/98192124/183285922-fa23a571-58ae-410c-bf82-b01dc6eecae6.png)

**Comment by makiuchi-d** [comment]
Your program looks fine, but the QR code in that image is terribly blurry and distorted.
