### ISSUE TITLE
wechat miniprogram qrcode parse error

### ISSUE THREAD

**Issue by Leadrive** [makiuchi-d/gozxing#55]
result, err := qrReader.Decode(bmp, nil)
NotFoundException: startSize = 0
![1485982252__8393d5fa6b9041fb8c5137cd1c2c618d](https://user-images.githubusercontent.com/16882802/224321487-bb827a47-a081-4af6-a51d-8df3934d7b78.jpeg)

**Comment by makiuchi-d** [comment]
It is not a QR-code.
