### ISSUE TITLE
NotFoundException: dimension = 75

### ISSUE THREAD

**Issue by tsywkGo** [makiuchi-d/gozxing#59]
My QR Code like this:
![image](https://github.com/makiuchi-d/gozxing/assets/63803593/ea687b54-fcbf-483e-afb1-cb489e34eae5)

when use Decode, this error happened:
`qrcode.NewQRCodeReader().Decode error:NotFoundException: dimension = 75`  

What could be the reason?

This QR Code picture can be scanned by WeChat to get the result.

**Comment by makiuchi-d** [comment]
That image is distorted and binarized in a bad way.
Each cell is not the same size.
If it is read, it is by chance.

**Comment by tsywkGo** [comment]
But, I can scan with Alipay and get the result.
