### ISSUE TITLE
Scanning of code 128

### ISSUE THREAD

**Issue by alhaos** [makiuchi-d/gozxing#63]
I found code 128 checkmarked on README and it is available to scan. But I found only QR code example, and code 128 failed to read.

How can I currently scan code 128?

**Comment by makiuchi-d** [comment]
use `oned.Code128Reader`:

```
reader := oned.NewCode128Reader()
result, _ := reader.Decode(bmp, nil)
```

**Comment by alhaos** [comment]
Thanks.
