### ISSUE TITLE
NotFoundException: startSize = 0

### ISSUE THREAD

**Issue by wangyu122-tal** [makiuchi-d/gozxing#64]
I am currently facing an issue with the QR code decoding process. Specifically, I am consistently receiving a NotFoundException with the message startSize = 0.

example qrcode:

![output](https://github.com/makiuchi-d/gozxing/assets/132868946/3bb263d0-af3f-43d7-b736-bd5a31070194)

I have tried several solutions suggested in other issues and on StackOverflow, but none of them have resolved my problem.

Could you please help me understand what might be causing this issue and suggest potential ways to resolve it? Any assistance would be greatly appreciated!

Thank you for your time and consideration.

**Comment by makiuchi-d** [comment]
This image lacks a quiet zone, and gozxing (ZXing) does not support negative color.

You must process the image before scanning:
```go
	w, h := img.Bounds().Max.X, img.Bounds().Max.Y
	img2 := image.NewRGBA(image.Rect(0, 0, w*2, h*2))
	draw.Draw(img2, image.Rect(w/2, h/2, w*3/2, h*3/2), img, image.Pt(0, 0), draw.Over)
	for y := 0; y < h*2; y++ {
		for x := 0; x < w*2; x++ {
			c := color.White
			if r, _, _, _ := img2.At(x, y).RGBA(); r > 60000 {
				c = color.Black
			}
			img2.Set(x, y, c)
		}
	}
```

I got a result:
```
https://channels.weixin.qq.com/promote/pages/mobile_login?token=AQAAAFN8wGwRamWEeeZHdA
```
