### ISSUE TITLE
How to handle: error creating code128

### ISSUE THREAD

**Issue by jaskierrr** [makiuchi-d/gozxing#66]
An error started appearing out of nowhere
error creating code128:  WriterException: IllegalArgumentException: Bad character in input: ASCII value=1042

I send only Latin letters, numbers, _, -
But when starting, an error appears

**Comment by makiuchi-d** [comment]
The error message says that there is a non ascii character `В`.
https://www.codetable.net/decimal/1042

**Comment by jaskierrr** [comment]
one day Cyrillic will kill someone, thx
